all: procesoA procesoB procesoC

procesoA: procesoA.c
	cc procesoA.c -o procesoA -Wno-incompatible-pointer-types

procesoB: procesoB.c
	cc procesoB.c -o procesoB -Wno-incompatible-pointer-types

procesoC: procesoC.c
	cc procesoC.c -o procesoC -Wno-incompatible-pointer-types